### ISSUE TITLE
IslandWorthUpdateEvent failed

### ISSUE THREAD

**Issue by FrancyMak** [BG-Software-LLC/SuperiorSkyblock2-NashornEngine#1]
[12:27:41 ERROR]: Could not pass event IslandWorthUpdateEvent to SuperiorSkyblock2 v1.7.0-DEVb209
java.lang.IllegalAccessError: failed to access class org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator$JumpTarget from class org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator (org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator$JumpTarget is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @37fadcf8; org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator is in unnamed module of loader com.bgsoftware.superiorskyblock.modules.ModuleClassLoader @4d812bbd)
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.createJumpTarget(LocalVariableTypesCalculator.java:419) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.getOrCreateJumpTarget(LocalVariableTypesCalculator.java:1196) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.jumpToLabel(LocalVariableTypesCalculator.java:1234) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.jumpToLabel(LocalVariableTypesCalculator.java:1230) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.enterBinaryNode(LocalVariableTypesCalculator.java:457) ~[?:?]
        at org.openjdk.nashorn.internal.ir.BinaryNode.accept(BinaryNode.java:329) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.visitExpression(LocalVariableTypesCalculator.java:603) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.enterBinaryNode(LocalVariableTypesCalculator.java:461) ~[?:?]
        at org.openjdk.nashorn.internal.ir.BinaryNode.accept(BinaryNode.java:329) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.visitExpression(LocalVariableTypesCalculator.java:603) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.visitExpressionOnEmptyStack(LocalVariableTypesCalculator.java:598) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.enterExpressionStatement(LocalVariableTypesCalculator.java:580) ~[?:?]
        at org.openjdk.nashorn.internal.ir.ExpressionStatement.accept(ExpressionStatement.java:81) ~[?:?]
        at org.openjdk.nashorn.internal.ir.Node.accept(Node.java:286) ~[?:?]
        at org.openjdk.nashorn.internal.ir.Block.accept(Block.java:236) ~[?:?]
        at org.openjdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57) ~[?:?]
        at org.openjdk.nashorn.internal.ir.Block.accept(Block.java:507) ~[?:?]
        at org.openjdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:405) ~[?:?]
        at org.openjdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57) ~[?:?]
        at org.openjdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:47) ~[?:?]
        at org.openjdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:57) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CompilationPhase.transformFunction(CompilationPhase.java:618) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CompilationPhase$LocalVariableTypeCalculationPhase.transform(CompilationPhase.java:277) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.CompilationPhase.apply(CompilationPhase.java:614) ~[?:?]
        at org.openjdk.nashorn.internal.codegen.Compiler.compile(Compiler.java:641) ~[?:?]
        at org.openjdk.nashorn.internal.runtime.Context.compile(Context.java:1528) ~[?:?]
        at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:1449) ~[?:?]
        at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:759) ~[?:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:528) ~[?:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:517) ~[?:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:395) ~[?:?]
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:151) ~[?:?]
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233) ~[java.scripting:?]
        at com.bgsoftware.superiorskyblock.scripts.NashornScript.eval(NashornScript.java:41) ~[?:?]
        at com.bgsoftware.superiorskyblock.missions.IslandMissions.tryComplete(IslandMissions.java:204) ~[?:?]
        at com.bgsoftware.superiorskyblock.missions.IslandMissions.tryComplete(IslandMissions.java:190) ~[?:?]
        at com.bgsoftware.superiorskyblock.missions.IslandMissions.onIslandWorthUpdate(IslandMissions.java:186) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor769.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Tuinity-"ac3aee1"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Tuinity-"ac3aee1"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"ac3aee1"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Tuinity-"ac3aee1"]
        at com.bgsoftware.superiorskyblock.utils.events.EventsCaller.callIslandWorthUpdateEvent(EventsCaller.java:193) ~[?:?]
        at com.bgsoftware.superiorskyblock.island.SIsland.lambda$saveBlockCounts$71(SIsland.java:2097) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Tuinity-"ac3aee1"]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Tuinity-"ac3aee1"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Tuinity-"ac3aee1"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by OmerBenGera** [comment]
This is a known issue that hopefully will be fixed soon.
I am closing this as theres qn already opened issue on SSB's tracker
